### ISSUE TITLE
Add simple extension to user model

### ISSUE THREAD

**Issue by deni** [2martens/chaos-dating#2]
The user model should be extended so that the project becomes a foundation for the dating app.

This should include:
* Gender (this one is tricky - which should we include?)
* Looking for (orientation)
* Tabs or spaces

I think we should deliberately postpone developing functionality for profile pictures, since that one is tricky (all uploaded pictures should be stripped for metadata and converted to a common format).

What do you think? Do we need any other fields? :)

Love
Deni :feet:

**Comment by 2martens** [comment]
I would start with three options in gender: female, male, diverse with the ability for users to create a new gender when opening their profile. The newly created gender is then added to the list of genders and available to all future users to select.

For "looking for" I would simply offer a multi-select of all existing genders in the application. Behind every gender could be a parentheses with the number of users that have selected that gender. 

There might be more fields but for starters it should suffice.

**Comment by deni** [comment]
Awesome idea. Will get started.

**Comment by deni** [comment]
Ok. So this one is interesting. I might be interested in girls, but only for friendships, whereas I could be interested in boys for dates. We need to allow one to specify multiple interests that can be confined to genders.

**Comment by 2martens** [comment]
Imagine the Friends/Sex/Relationship settings of Romeo multiplied with gender.

**Comment by deni** [comment]
I did something really cool. Looking forward to showing you.

**Comment by 2martens** [comment]
An additional field should be pronoun as a simple CharField.
